### ISSUE TITLE
No script named mysqlstats.pl in folder

### ISSUE THREAD

**Issue by walertos86** [bernisys/cacti-templates#1]
Empty result [127.0.0.1]: 'perl /var/www/cacti/scripts/mysqlstats.pl query'
 'perl /var/www/cacti/scripts/mysqlstats.pl inno_rows'
 'perl /var/www/cacti/scripts/mysqlstats.pl connections'
 InnoDB Memory] ERROR: Empty result [127.0.0.1]: 'perl /var/www/cacti/scripts/mysqlstats.pl inno_mem'
 DB Statistics - Boost] Graphs[BILLING SERVER - Cacti DB Stats - Boost] ERROR: Empty result [127.0.0.1]: 'perl /var/www/cacti/scripts/mysqlstats.pl boost'

**Comment by bernisys** [comment]
Thanks for noticing! Will take a look into it.

**Comment by bernisys** [comment]
@walertos86: please pull & check - should be working now.
I accidentally ported the wrong script (older version) into github
